/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Teste;

import Class.Bin;
import Class.Seconds;
import Class.Trash;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;


/**
 *
 * @author é o r's
 */
public class ProjectExec extends javax.swing.JFrame {
    
    ArrayList<Trash> trashlist = new ArrayList<Trash>();
    Seconds seconds;
    Thread tSec;
    
        
    int score = 0;
    Trash trash11 = new Trash("paper ball", "paper");

    Trash trash22 = new Trash("glass bottle", "glass");

    Trash trash33 = new Trash("can of soda", "metal");


    Bin bin = new Bin("blue","paper");
        
    
    
    
    /**
     * Creates new form ProjectExec
     */
    public ProjectExec() {
        initComponents();
        trashlist.add(trash11);
        trashlist.add(trash22);
        trashlist.add(trash33);
        
        Random rgd = new Random();
        
        int lixo1 = rgd.nextInt(trashlist.size());
        int lixo2 = rgd.nextInt(trashlist.size());
        int lixo3 = rgd.nextInt(trashlist.size());
        
        while (lixo2 == lixo1) {
            lixo2 = rgd.nextInt(trashlist.size());
        }
        while (lixo3 == lixo1 || lixo3 == lixo2) {
            lixo3 = rgd.nextInt(trashlist.size());
        }
        
        Trash lixoEscolhido1 = trashlist.get(lixo1);
        Trash lixoEscolhido2 = trashlist.get(lixo2);
        Trash lixoEscolhido3 = trashlist.get(lixo3);
        
        seconds = new Seconds();
        tSec = new Thread(seconds);            
        
     
        trash1.setText(lixoEscolhido1.getTrash());
        
        trash2.setText(lixoEscolhido2.getTrash());
        
        trash3.setText(lixoEscolhido3.getTrash());
        
        binGame.setText(bin.getColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSeconds = new javax.swing.JLabel();
        binGame = new javax.swing.JLabel();
        trash1 = new javax.swing.JButton();
        trash2 = new javax.swing.JButton();
        trash3 = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Time:");

        txtSeconds.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtSeconds.setText("0");

        binGame.setText("jLabel2");

        trash1.setText("jButton2");
        trash1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trash1ActionPerformed(evt);
            }
        });

        trash2.setText("jButton1");
        trash2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trash2ActionPerformed(evt);
            }
        });

        trash3.setText("jButton2");
        trash3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trash3ActionPerformed(evt);
            }
        });

        lblScore.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblScore.setText("0");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Score:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(trash1)
                        .addGap(31, 31, 31)
                        .addComponent(trash2)
                        .addGap(27, 27, 27)
                        .addComponent(trash3)
                        .addGap(300, 300, 300))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(binGame)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtSeconds)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSeconds)
                    .addComponent(lblScore)
                    .addComponent(jLabel2))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trash1)
                    .addComponent(trash2)
                    .addComponent(trash3))
                .addGap(59, 59, 59)
                .addComponent(binGame)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        tSec.start();
    }//GEN-LAST:event_formWindowActivated

    private void trash1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trash1ActionPerformed
        // TODO add your handling code here:
        if(trash11.getCategoryTrash().equals(bin.getCategoryBin())) {
            JOptionPane.showMessageDialog(null, "Parabéns");
            score = score + 1;
            String scoreString = Integer.toString(score);
            lblScore.setText(scoreString);      
        } else {
            this.dispose();
            GameOver go = new GameOver();
            go.setVisible(true);
        }
    }//GEN-LAST:event_trash1ActionPerformed

    private void trash2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trash2ActionPerformed
        // TODO add your handling code here:
        if(trash22.getCategoryTrash().equals(bin.getCategoryBin())) {
            JOptionPane.showMessageDialog(null, "Parabéns");
            score = score + 1;
            String scoreString = Integer.toString(score);
            lblScore.setText(scoreString);   
        } else {
            this.dispose();
            GameOver go = new GameOver();
            go.setVisible(true);
        }
    }//GEN-LAST:event_trash2ActionPerformed

    private void trash3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trash3ActionPerformed
        // TODO add your handling code here:
        if(trash33.getCategoryTrash().equals(bin.getCategoryBin())) {
            JOptionPane.showMessageDialog(null, "Parabéns");
            score = score + 1;
            String scoreString = Integer.toString(score);
            lblScore.setText(scoreString);   
        } else {
            this.dispose();
            GameOver go = new GameOver();
            go.setVisible(true);
        }
    }//GEN-LAST:event_trash3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectExec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectExec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectExec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectExec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectExec().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel binGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblScore;
    private javax.swing.JButton trash1;
    private javax.swing.JButton trash2;
    private javax.swing.JButton trash3;
    public static javax.swing.JLabel txtSeconds;
    // End of variables declaration//GEN-END:variables
}
